### ISSUE TITLE
Old katex version.

### ISSUE THREAD

**Issue by discharged-spider** [dhruv004/React-Tex#1]
Hi!
Your package uses outdated katex version, so new .css file from the latest (0.8.3) version not work properly. Could you fix it, please?

**Comment by dhruv004** [comment]
What exactly is not working.?Do you want me to update katex.?

**Comment by discharged-spider** [comment]
For example, fractions.
Yes, if you could update katex dependency to the latest version, all will be ok. (tested myself)

**Comment by dhruv004** [comment]
Closing this. @yam-b has updated the katex dependency
